Document: say-hello
Title: Debian say-hello Manual
Author: <insert document author here>
Abstract: This manual describes what say-hello is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/say-hello/say-hello.sgml.gz

Format: postscript
Files: /usr/share/doc/say-hello/say-hello.ps.gz

Format: text
Files: /usr/share/doc/say-hello/say-hello.text.gz

Format: HTML
Index: /usr/share/doc/say-hello/html/index.html
Files: /usr/share/doc/say-hello/html/*.html
